spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product_service
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8080 # Your desired server port

logging:
  level:
    root: INFO # Adjust log level as needed

# Other application-specific configurations
