app:
  eureka-hostname: localhost
  eureka-port: 8761
  database-hostname: localhost
  database-port: 5432
  database-name: product_service
  server-port: 8081
  #  server-port: 0
  application-name: product-service
  kafka-hostname: localhost
  kafka-port: 9092
  kafka-default-topic: notificationTopic
  kafka-concurrency: 3
  kafka-group-id: notificationId
  context-path: api/product
  api-gateway-hostname: localhost
  api-gateway-server-port: 8181

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-hostname}:${app.eureka-port}/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5


spring:
  application:
    name: ${app.application-name}
  flyway:
    baseline-on-migrate: true
    baseline-version: 0.0
    locations: classpath:db/migration/
    validate-on-migrate: true
    enabled: true
    table: schema_history
  kafka:
    enabled: true
    bootstrap-servers: ${app.kafka-hostname}:${app.kafka-port}
    template:
      default-topic: ${app.kafka-default-topic}
    producers:
      internal-producer:
        topic-name: internalTopic
      notification-producer:
        topic-name: notificationTopic
  #    producer:
  #      properties:

  datasource:
    url: jdbc:postgresql://${app.database-hostname}:${app.database-port}/${app.database-name}
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

    show-sql: true

management:
  tracing:
    enabled: true
    propagation:
      type: b3
    sampling:
      probability: 1.0
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

server:
  port: ${app.server-port}
  servlet:
    context-path: /${app.context-path}

logging:
  level:
    root: INFO
  pattern:
    level: "%5p[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"


springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

swagger:
  server:
    url: http://${app.api-gateway-hostname}:${app.api-gateway-server-port}/${app.context-path}