BEGIN;

CREATE TABLE IF NOT EXISTS PRODUCT
(
    ID                 BIGSERIAL PRIMARY KEY,
    NAME               VARCHAR(255)   NOT NULL,
    DESCRIPTION        TEXT,
    PRICE              NUMERIC(19, 4) NOT NULL,
    CATEGORY_ID        BIGINT,
    CREATED_BY         VARCHAR(255),
    CREATED_DATE       TIMESTAMP(6),
    LAST_MODIFIED_BY   VARCHAR(255),
    LAST_MODIFIED_DATE TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS CATEGORY
(
    ID                 BIGSERIAL PRIMARY KEY,
    NAME               VARCHAR(255) NOT NULL,
    CREATED_BY         VARCHAR(255),
    CREATED_DATE       TIMESTAMP(6),
    LAST_MODIFIED_BY   VARCHAR(255),
    LAST_MODIFIED_DATE TIMESTAMP(6)
);

COMMIT;