BEGIN;

CREATE OR REPLACE VIEW PRODUCT_VIEW AS
SELECT T1.ID,
       T1.NAME,
       T1.DESCRIPTION,
       T1.PRICE,
       T1.CREATED_BY,
       T1.CREATED_DATE,
       T1.LAST_MODIFIED_BY,
       T1.LAST_MODIFIED_DATE,
       T2.NAME AS CATEGORY_NAME
FROM PRODUCT T1
         INNER JOIN CATEGORY T2 ON T2.ID = T1.CATEGORY_ID;

COMMIT;